default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: timofey
  password:
  timeout: 5000

development:
  <<: *default
  database: topgh_development

test:
  <<: *default
  database: topgh_test

production:
  <<: *default
  database: topgh_production
